spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
app:
  consumer:
   queue: scheduledq
  receiver:
    exchange: delayed.dx
    routingKey: delay